#include "nw_i0_tool"
/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();

RewardPartyXP(700, oPC, TRUE);

object oItem;
oItem = GetItemPossessedBy(oPC, "qst_earthrelic");

if (GetIsObjectValid(oItem))
   DestroyObject(oItem);

}
