/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (GetHitDice(oPC) <  35) return FALSE;

if (GetAlignmentGoodEvil(oPC) != ALIGNMENT_EVIL) return FALSE;

if (!GetHasSkill(SKILL_BLUFF, oPC)) return FALSE;

return TRUE;
}

