// prc_onenter,x3_mod_def_enter
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the oncliententer event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onenter", OBJECT_SELF);
    ExecuteScript("ar_mod_onenter", OBJECT_SELF);
}
