// prc_onrespawn, ar_mod_onrespawn
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrespawn event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onrespawn", OBJECT_SELF);
    ExecuteScript("ar_mod_onrespawn", OBJECT_SELF);
}
