// prc_oncutabort, ar_mod_cutabort
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onacquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_oncutabort", OBJECT_SELF);
    ExecuteScript("ar_mod_cutabort", OBJECT_SELF);
}
