// prc_onheartbeat, ar_mod_hearbeat
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onheatbeat event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onheartbeat", OBJECT_SELF);
    ExecuteScript("ar_mod_onhb", OBJECT_SELF);
}
