// prc_levelup, ar_onlevelup
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerequipitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_levelup", OBJECT_SELF);
    ExecuteScript("ar_mod_onlevelup", OBJECT_SELF);
}
