// prc_onunaquire, ar_mod_onunaqui
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onunaquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onunaquire", OBJECT_SELF);
    ExecuteScript("ar_mod_onunaqui", OBJECT_SELF);
}
