/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (GetItemPossessedBy(oPC, "sokidocument") == OBJECT_INVALID) return FALSE;

if (GetLocalInt(oPC, "maddoxapproves") != 1) return FALSE;

int nInt;
nInt=GetLocalInt(oPC, "NW_JOURNAL_ENTRYUrikTemplars");

if (nInt < 1)
   return FALSE;

return TRUE;
}
