/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (GetItemPossessedBy(oPC, "QST_HIGHBUREAU01") == OBJECT_INVALID) return FALSE;

int nInt;
nInt=GetLocalInt(oPC, "NW_JOURNAL_ENTRYTheTemplars");

if (GetLocalInt(oPC, "yehinaapproves") != 1) return FALSE;

return TRUE;
}

