/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (GetItemPossessedBy(oPC, "QST_SHADEMESSAGE") == OBJECT_INVALID) return FALSE;

if (!(GetLocalInt(oPC, "seleneapproves") == 1)) return FALSE;

int nInt;
nInt=GetLocalInt(oPC, "NW_JOURNAL_ENTRYTheDraqomen");

if (!(nInt == 2))
   return FALSE;

return TRUE;
}

