/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (!(GetHitDice(oPC) >=  3)) return FALSE;

if (!(GetHitDice(oPC) <=  7)) return FALSE;

return TRUE;
}

