// prc_ondying, ar_mod_ondying
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerdying event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_ondying", OBJECT_SELF);
    ExecuteScript("ar_mod_ondying", OBJECT_SELF);
}
