// prc_onleave, ar_def_onleave
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onacquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onleave", OBJECT_SELF);
    ExecuteScript("ar_mod_onleave", OBJECT_SELF);
}
