// prc_rest, ar_mod_onrest
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrest event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_rest", OBJECT_SELF);
    ExecuteScript("ar_mod_onrest", OBJECT_SELF);
}
