/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();

AdjustAlignment(oPC, ALIGNMENT_EVIL, 10);

object oTarget;
oTarget = OBJECT_SELF;

AdjustReputation(oPC, oTarget, -100);

SetLocalInt(oPC, "TARIKILLER", 1);

}

