#include "nw_i0_tool"
/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();

RewardPartyXP(300, oPC, FALSE);

RewardPartyGP(300, oPC, FALSE);

CreateItemOnObject("FAC_ITPNCK_TYRTM", oPC);

CreateItemOnObject("FAC_KEY_TYRTEMP", oPC);

CreateItemOnObject("fac_helm_tyrtmp", oPC);

}
