/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */
const int FEAT_MAGMA_DOMAIN_POWER = 5018;
int StartingConditional()
{
object oPC = GetPCSpeaker();

if (!GetHasFeat(FEAT_MAGMA_DOMAIN_POWER, oPC)) return FALSE;

return TRUE;
}
